apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
- namespace.yaml
images:
- digest: sha256:49326d20e7985d1168a33b8a7a4f89e7576fccf3f95e3f945385ae7e1c7c8508
  name: quay.io/sachinayyar/node-login
  newName: quay.io/sachinayyar/node-login:latest
